# Site
name: "Chleby Rolfa | Przepis"
title: "Chleby Rolfa | Przepis krok po kroku"
description: "Przepisy krok po kroku, gotowe na śniadanie, bez wstawania w środku nocy. Jak upiec chleb w domu? Świeżutki, pachnący, chrupiący, na zakwasie i na drożdżach."
logo: 'assets/images/icons/logo.png'
favicon: 'assets/images/icons/logo.png'
url: https://www.chlebyrolfa.pl
baseurl:
google_analytics: 'UA-164126054-1'
disqus: 'chlebyrolfa'
mailchimp-list: 'https://chlebyrolfa.us10.list-manage.com/subscribe/post?u=8ed4c03298a0bf66a9f4206f6&amp;id=a250c2380c'
include: ["_pages"]
permalink: /:title/
future: true
lang: pl_PL
locale: pl_PL
excerpt_separator: "## Składniki"
feed:
  posts_limit: 20

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
   
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  sort_reverse: true
  per_page: 12
  permalink: '/page/:num/'
  category: 'posts'
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

minified_css: true

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

see_also: true
