# Site
name: "Chleby Rolfa"
title: "Chleby Rolfa"
description: "Przepisy krok po kroku, gotowe na śniadanie, bez wstawania w środku nocy. Jak upiec chleb w domu? Świeżutki, pachnący, chrupiący, na zakwasie i na drożdżach, z rozmaitymi ziołami, ziarnami i przyprawami. Swoista akademia piekarza i warsztaty chlebowe. Znajdź przepis na chleb, który łatwo upieczesz w swojej kuchni."
main-header: "Przepisy krok po kroku, gotowe na śniadanie, bez wstawania w środku nocy."
logo: 'assets/images/icons/logo.png'
favicon: 'assets/images/icons/logo.png'
baseurl:
google_analytics: 'UA-164126054-1'
disqus: 'chlebyrolfa'
include: ["_pages"]
permalink: /:title/
future: true
lang: pl_PL
locale: pl_PL

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
